hello_www/config/routes.rb
Rails.application.routes.draw do
  resources :pionners
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

hello_www/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hello_www/app/models/pionner.rb
class Pionner < ApplicationRecord
end

hello_www/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

hello_www/app/controllers/pionners_controller.rb
class PionnersController < ApplicationController
  before_action :set_pionner, only: [:show, :edit, :update, :destroy]

  # GET /pionners
  # GET /pionners.json
  def index
    @pionners = Pionner.all
  end

  # GET /pionners/1
  # GET /pionners/1.json
  def show
  end

  # GET /pionners/new
  def new
    @pionner = Pionner.new
  end

  # GET /pionners/1/edit
  def edit
  end

  # POST /pionners
  # POST /pionners.json
  def create
    @pionner = Pionner.new(pionner_params)

    respond_to do |format|
      if @pionner.save
        format.html { redirect_to @pionner, notice: 'Pionner was successfully created.' }
        format.json { render :show, status: :created, location: @pionner }
      else
        format.html { render :new }
        format.json { render json: @pionner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pionners/1
  # PATCH/PUT /pionners/1.json
  def update
    respond_to do |format|
      if @pionner.update(pionner_params)
        format.html { redirect_to @pionner, notice: 'Pionner was successfully updated.' }
        format.json { render :show, status: :ok, location: @pionner }
      else
        format.html { render :edit }
        format.json { render json: @pionner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pionners/1
  # DELETE /pionners/1.json
  def destroy
    @pionner.destroy
    respond_to do |format|
      format.html { redirect_to pionners_url, notice: 'Pionner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pionner
      @pionner = Pionner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pionner_params
      params.require(:pionner).permit(:first_name, :last_name)
    end
end

hello_www/app/helpers/application_helper.rb
module ApplicationHelper
end

hello_www/app/helpers/pionners_helper.rb
module PionnersHelper
end

hello_www/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWww</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

hello_www/app/views/pionners/_form.html.erb
<%= form_for(pionner) do |f| %>
  <% if pionner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pionner.errors.count, "error") %> prohibited this pionner from being saved:</h2>

      <ul>
      <% pionner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hello_www/app/views/pionners/edit.html.erb
<h1>Editing Pionner</h1>

<%= render 'form', pionner: @pionner %>

<%= link_to 'Show', @pionner %> |
<%= link_to 'Back', pionners_path %>

hello_www/app/views/pionners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pionners</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pionners.each do |pionner| %>
      <tr>
        <td><%= pionner.first_name %></td>
        <td><%= pionner.last_name %></td>
        <td><%= link_to 'Show', pionner %></td>
        <td><%= link_to 'Edit', edit_pionner_path(pionner) %></td>
        <td><%= link_to 'Destroy', pionner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pionner', new_pionner_path %>

hello_www/app/views/pionners/new.html.erb
<h1>New Pionner</h1>

<%= render 'form', pionner: @pionner %>

<%= link_to 'Back', pionners_path %>

hello_www/app/views/pionners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @pionner.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @pionner.last_name %>
</p>

<%= link_to 'Edit', edit_pionner_path(@pionner) %> |
<%= link_to 'Back', pionners_path %>